---
spring:
  zipkin:
    base-url=http://localhost:9411
  sleuth:
    messaging:
      kafka:
        streams:
          enabled: true
  config:
    activate:
      on-profile: "local"
  cloud:
    stream:
      bindings:
        input-channel:
          destination: message
        output-channel:
          destination: validate
      kafka:
        streams:
          binder:
            deserialization-exception-handler: sendToDlq
            applicationId: ruleengineApp
            brokers: localhost:9092
            configuration:
              processing.guarantee: exactly_once_v2
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            output-channel:
              producer:
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              consumer:
                dlqName: topic-error
---
spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
    stream:
      bindings:
        input-channel:
          destination: message
        output-channel:
          destination: validate
      kafka:
        streams:
          binder:
            deserialization-exception-handler: sendToDlq
            applicationId: ruleengineApp
            brokers: localhost:9092
            configuration:
              processing.guarantee: exactly_once_v2
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            output-channel:
              producer:
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              consumer:
                dlqName: topic-error
---
spring:
  config:
    activate:
      on-profile: "prod"
  cloud:
    stream:
      bindings:
        input-channel:
          destination: message
        output-channel:
          destination: validate
      kafka:
        streams:
          binder:
            deserialization-exception-handler: sendToDlq
            applicationId: ruleengineApp
            brokers: localhost:9092
            configuration:
              processing.guarantee: exactly_once_v2
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            output-channel:
              producer:
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              consumer:
                dlqName: topic-error
---

spring:
  application:
    name: service-ruleengine
  profiles:
    active: "local"

server:
  port: 7400

logging:
  level:
    root: INFO
